name: thermion_flutter_example
description: Demonstrates how to use the thermion_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  thermion_flutter:
    path: ../../../thermion_flutter/thermion_flutter
  cupertino_icons: ^1.0.2
  web:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  crypto:
  image_compare: ^1.1.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/shapes/
    - assets/default_env/
    - assets/BusterDrone/
    - assets/BusterDrone/textures/
    - assets/FlightHelmet/
  