name: thermion_dart
description: 3D rendering toolkit for Dart.
version: 0.2.1-dev.20.0
homepage: https://thermion.dev
repository: https://github.com/nmfisher/thermion

environment:
  sdk: ">=3.6.0-0 <4.0.0"

dependencies:
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  ffi: ^2.1.2
  animation_tools_dart: ^0.1.0
  native_toolchain_c: ^0.4.2
  native_assets_cli: ^0.6.1
  archive: ^3.6.1
  web: ^1.0.0
  logging: ^1.2.0
  http: ^1.2.2
  path: ^1.9.0
  
dev_dependencies:
  ffigen: ^13.0.0
  objective_c: ^1.1.0
  test:
  image:
  path:
  mockito: ^5.0.0
  build_runner: ^2.0.0
  